In [6]:
import pandas as pd

## Reading NHANES orginal data_class

In [7]:
data = pd.read_csv('../Data/data_class.csv')
data

,Unnamed: 0,SEQN,RIAGENDR,RIDAGEYR,DMDHHSIZ,INDFMPIR,BMXBMI,DSD010,DSD010AN,SMD415,...,protein,healthy,unhealthy,beverage,milk,MCQ010,MCQ053,MCQ092,MCQ140,active
0,0,21005.0,1.0,19.0,2.0,2.44,50.85,0.0,0.0,0.0,...,82.0,73.0,108.0,3.0,10.0,0.0,0.0,0.0,0.0,1
1,1,21006.0,2.0,16.0,6.0,2.47,20.78,0.0,0.0,1.0,...,100.0,94.0,137.0,3.0,10.0,0.0,0.0,0.0,0.0,0
2,2,21007.0,2.0,14.0,5.0,1.60,18.43,0.0,0.0,1.0,...,62.0,92.0,95.0,4.0,14.0,0.0,0.0,0.0,0.0,0
3,3,21008.0,1.0,17.0,7.0,2.75,20.65,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
4,4,21009.0,1.0,55.0,2.0,3.79,31.26,0.0,0.0,0.0,...,87.0,111.0,121.0,7.0,13.0,0.0,0.0,0.0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12563,12563,41469.0,1.0,19.0,2.0,0.66,19.25,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12564,12564,41471.0,1.0,12.0,5.0,0.35,18.41,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
12565,12565,41472.0,1.0,34.0,2.0,3.66,26.23,1.0,0.0,0.0,...,90.0,85.0,133.0,17.0,19.0,0.0,0.0,0.0,0.0,0
12566,12566,41473.0,1.0,21.0,6.0,1.16,26.16,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
12567,12567,41474.0,2.0,16.0,5.0,0.31,25.08,0.0,0.0,0.0,...,103.0,90.0,150.0,5.0,13.0,0.0,0.0,0.0,0.0,0

In [8]:
data.columns

Index(['Unnamed: 0', 'SEQN', 'RIAGENDR', 'RIDAGEYR', 'DMDHHSIZ', 'INDFMPIR',
       'BMXBMI', 'DSD010', 'DSD010AN', 'SMD415', 'PAD590', 'PAD600', 'HUQ010',
       'restaurant', 'protein', 'healthy', 'unhealthy', 'beverage', 'milk',
       'MCQ010', 'MCQ053', 'MCQ092', 'MCQ140', 'active'],
      dtype='object')

## Converting columns to sensible names

In [9]:
data.rename(columns={
    'Unnamed: 0': 'Index',
    'SEQN': 'Respondent ID',
    'RIAGENDR': 'Gender',
    'RIDAGEYR': 'Age',
    'DMDHHSIZ': 'Household Size',
    'INDFMPIR': 'Income Poverty Ratio',
    'BMXBMI': 'BMI',
    'DSD010': 'Diet Question',
    'DSD010AN': 'Diet Question Annotation',
    'SMD415': 'Smoking Status',
    'PAD590': 'Physical Activity Frequency',
    'PAD600': 'Physical Activity Duration',
    'HUQ010': 'General Health Status',
    'restaurant': 'Restaurant Visits',
    'protein': 'Protein Intake',
    'healthy': 'Healthy Food Intake',
    'unhealthy': 'Unhealthy Food Intake',
    'beverage': 'Beverage Consumption',
    'milk': 'Milk Consumption',
    'MCQ010': 'Medical Condition 1',
    'MCQ053': 'Medical Condition 2',
    'MCQ092': 'Medical Condition 3',
    'MCQ140': 'Medical Condition 4',
    'active': 'Physical Activity Status'
}, inplace=True)


data.head()

,Index,Respondent ID,Gender,Age,Household Size,Income Poverty Ratio,BMI,Diet Question,Diet Question Annotation,Smoking Status,...,Protein Intake,Healthy Food Intake,Unhealthy Food Intake,Beverage Consumption,Milk Consumption,Medical Condition 1,Medical Condition 2,Medical Condition 3,Medical Condition 4,Physical Activity Status
0,0,21005.0,1.0,19.0,2.0,2.44,50.85,0.0,0.0,0.0,...,82.0,73.0,108.0,3.0,10.0,0.0,0.0,0.0,0.0,1
1,1,21006.0,2.0,16.0,6.0,2.47,20.78,0.0,0.0,1.0,...,100.0,94.0,137.0,3.0,10.0,0.0,0.0,0.0,0.0,0
2,2,21007.0,2.0,14.0,5.0,1.60,18.43,0.0,0.0,1.0,...,62.0,92.0,95.0,4.0,14.0,0.0,0.0,0.0,0.0,0
3,3,21008.0,1.0,17.0,7.0,2.75,20.65,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0
4,4,21009.0,1.0,55.0,2.0,3.79,31.26,0.0,0.0,0.0,...,87.0,111.0,121.0,7.0,13.0,0.0,0.0,0.0,0.0,1

## Chossing a subset of columns to work with

In [10]:
# Dropping the specified columns
columns_to_drop = [
    'Index', 
    'Respondent ID', 
    'Physical Activity Frequency', 
    'Physical Activity Duration', 
    'Medical Condition 1', 
    'Medical Condition 2', 
    'Medical Condition 3', 
    'Medical Condition 4'
]

data.drop(columns=columns_to_drop, inplace=True)

# Verify changes
data.head()

,Gender,Age,Household Size,Income Poverty Ratio,BMI,Diet Question,Diet Question Annotation,Smoking Status,General Health Status,Restaurant Visits,Protein Intake,Healthy Food Intake,Unhealthy Food Intake,Beverage Consumption,Milk Consumption,Physical Activity Status
0,1.0,19.0,2.0,2.44,50.85,0.0,0.0,0.0,3.0,0.0,82.0,73.0,108.0,3.0,10.0,1
1,2.0,16.0,6.0,2.47,20.78,0.0,0.0,1.0,2.0,2.0,100.0,94.0,137.0,3.0,10.0,0
2,2.0,14.0,5.0,1.60,18.43,0.0,0.0,1.0,2.0,2.0,62.0,92.0,95.0,4.0,14.0,0
3,1.0,17.0,7.0,2.75,20.65,0.0,0.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0
4,1.0,55.0,2.0,3.79,31.26,0.0,0.0,0.0,2.0,9.0,87.0,111.0,121.0,7.0,13.0,1

1. Gender
2. Age
3. Household Size
4. Income Poverty Ratio
5. BMI
6. Diet Question
7. Diet Question Annotation
8. Smoking Status
9. General Health Status
10. Restaurant Visits
11. Protein Intake
12. Healthy Food Intake
13. Unhealthy Food Intake
14. Beverage Consumption
15. Milk Consumption
- Physical Activity Status (Target Variable)

In [11]:
data.to_csv('../Data/total_data_class.csv')

## Universal Division or Train and Test Sets
- 60 - TRAIN
- 40 - TEST

- Trying to create a situation of less amount of data present

In [12]:
from sklearn.model_selection import train_test_split

# Define target column
target_column = 'Physical Activity Status'

# Split the data
train_data, test_data = train_test_split(data, test_size=0.4, random_state=42, stratify=data[target_column])

# Save to CSV
train_data.to_csv('../data/universal_train_data.csv', index=False)
test_data.to_csv('../data/universal_test_data.csv', index=False)

In [15]:
train_data

,Gender,Age,Household Size,Income Poverty Ratio,BMI,Diet Question,Diet Question Annotation,Smoking Status,General Health Status,Restaurant Visits,Protein Intake,Healthy Food Intake,Unhealthy Food Intake,Beverage Consumption,Milk Consumption,Physical Activity Status
7280,2.0,54.0,4.0,2.02,21.60,0.0,0.0,0.0,1.0,4.0,57.0,72.0,90.0,16.0,7.0,0
676,1.0,17.0,5.0,0.96,21.09,0.0,0.0,0.0,2.0,2.0,174.0,121.0,143.0,18.0,9.0,1
4584,2.0,15.0,4.0,2.17,21.84,0.0,0.0,1.0,2.0,4.0,112.0,129.0,154.0,7.0,16.0,0
10193,1.0,17.0,4.0,1.81,27.18,0.0,0.0,2.0,1.0,4.0,109.0,102.0,147.0,2.0,12.0,0
5708,2.0,30.0,2.0,4.13,32.19,1.0,1.0,0.0,1.0,3.0,72.0,103.0,92.0,4.0,12.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3230,1.0,18.0,6.0,0.22,22.81,0.0,0.0,0.0,3.0,16.0,116.0,123.0,156.0,15.0,24.0,0
471,1.0,11.0,5.0,0.95,18.18,0.0,0.0,1.0,1.0,3.0,76.0,34.0,128.0,3.0,15.0,0
10507,2.0,52.0,5.0,5.00,37.37,1.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0
722,1.0,15.0,5.0,0.64,20.66,0.0,0.0,0.0,1.0,2.0,118.0,106.0,137.0,5.0,14.0,1
10616,2.0,56.0,2.0,1.23,51.23,1.0,0.0,0.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,0

In [16]:
test_data.head

<bound method NDFrame.head of        Gender   Age  Household Size  Income Poverty Ratio    BMI  \
5366      1.0  43.0             4.0                  4.08  36.54
6476      1.0  11.0             7.0                  1.66  26.10
12203     1.0  19.0             4.0                  4.01  29.12
8691      2.0  32.0             3.0                  0.98  28.29
2374      2.0  34.0             3.0                  5.00  23.83
...       ...   ...             ...                   ...    ...
12555     1.0  19.0             4.0                  2.07  22.88
4835      1.0  83.0             2.0                  5.00  26.49
10104     2.0  62.0             2.0                  0.83  31.64
6041      1.0  12.0             3.0                  1.90  23.33
1115      2.0  12.0             4.0                  0.64  22.55

       Diet Question  Diet Question Annotation  Smoking Status  \
5366             0.0                       1.0             0.0
6476             0.0                       0.0             0.0
12203            1.0                       1.0             0.0
8691             1.0                       0.0             0.0
2374             0.0                       0.0             0.0
...              ...                       ...             ...
12555            0.0                       0.0             0.0
4835             1.0                       0.0             0.0
10104            1.0                       0.0             2.0
6041             0.0                       0.0             0.0
1115             1.0                       1.0             2.0

       General Health Status  Restaurant Visits  Protein Intake  \
5366                     3.0                5.0           105.0
6476                     3.0                7.0             0.0
12203                    2.0                9.0            99.0
8691                     3.0                1.0            84.0
2374                     1.0                1.0            81.0
...                      ...                ...             ...
12555                    1.0                1.0             0.0
4835                     2.0                3.0            88.0
10104                    3.0                0.0            85.0
6041                     3.0                3.0             0.0
1115                     2.0                0.0           128.0

       Healthy Food Intake  Unhealthy Food Intake  Beverage Consumption  \
5366                 162.0                  121.0                   3.0
6476                   0.0                    0.0                   0.0
12203                106.0                  147.0                   9.0
8691                 137.0                  103.0                   6.0
2374                 110.0                  114.0                  16.0
...                    ...                    ...                   ...
12555                  0.0                    0.0                   0.0
4835                 147.0                  122.0                   6.0
10104                131.0                   81.0                   6.0
6041                   0.0                    0.0                   0.0
1115                 127.0                  157.0                   8.0

       Milk Consumption  Physical Activity Status
5366               12.0                         0
6476                0.0                         0
12203              13.0                         0
8691               17.0                         0
2374               24.0                         0
...                 ...                       ...
12555               0.0                         0
4835               16.0                         0
10104              13.0                         0
6041                0.0                         1
1115               24.0                         0

[5028 rows x 16 columns]>